[package]
name = "parr"
version = "0.1.2"
edition = "2021"
authors = [ "Andrey baranov (andofwinds) <andrey@elib.ru>" ]
description = "A C-like unknown-length array type."
readme = "README.md"
repository = "https://github.com/andofwinds/parr"
license = "MPL-2.0"
keywords = ["osdev", "no-std", "c"]
